# This workflow will publish any new release to the npmjs registry

name: Publish

on:
  release:
    types: [created]

jobs:
  pre-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
      - run: npm ci --package-lock
      - run: npm test
      - run: npm lint:ci

  publish-npm:
    needs: pre-publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          registry-url: https://registry.npmjs.org/
      - run: npm ci --package-lock
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
